/**
 * This java source file was generated by the Gradle 'init' task.
 */

package gradle.demo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String someOtherMethod() { return "Hello, World!"; }
}
